name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Install pyinstaller
      run: pip3 install pyinstaller
    - name: Compile to exe
      run: pyinstaller main.py
